GET http://localhost:1234/ditto

###separacion

POST http://localhost:1234/pokemon
Content-Type: application/json

{
    "name":"ditto",
    "type":"normal",
    "moves":[
        "placaje",
        "ida y vueta"
    ]
}