GET http://localhost:1234/movies

### separacion
GET http://localhost:1234/movies?genre=action
### recuperar pelicula
GET http://localhost:1234/movies/58941694-d5e2-4cf7-84fc-0d08ca317507

### Crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The Dark Knight nuevfdghds",
    "year": 2008,
    "director": "fdjfhdfhdfh",
    "duration": 152,
    "poster": "https://i.ebayimg.com/images/g/yokAAOSw8w1YARbm/s-l1200.jpg",
    "genre": ["Action", "Drama"],
    "rate": 9.0
}
###

PATCH http://localhost:1234/movies/58941694-d5e2-4cf7-84fc-0d08ca317507
Content-Type: application/json

{
    "year":1999
}
###

DELETE http://localhost:1234/movies/58941694-d5e2-4cf7-84fc-0d08ca317507
